### ISSUE TITLE
Better JWT verification failure information and add "dat" documentation

### ISSUE THREAD

**Issue by psylinse** [haskell-servant/servant-auth#49] opened 2017-05-31 23:38 UTC
First off, thanks for making this. I have this successfully implemented and it does exactly what I need. I know this library is new, but want to give some feedback and see if I can help out. I'm fairly new to Haskell+Servant so I apologize if any of these are not issues with more knowledge.

One issue I had was dealing with `AuthResult` failures while trying to get everything to flow. What was difficult is when I received the `AuthResult` I had no insight into why it failed. For a long time I thought it was JWT configuration issues until I started pulling code out of the lib to see what was really happening. This part in particular:

https://github.com/plow-technologies/servant-auth/blob/ffa4c29c86f4deca8e183f2fb426e660e4551d9a/servant-auth-server/src/Servant/Auth/Server/Internal/JWT.hs#L62-L66 

Once I realized it was actually verifying correctly and it was just JWT decode issues on my type, it was easy to get it going.

Another issue was not realizing that it was looking in unregistered claims for the keyword "dat".  I'm using Auth0 to generate tokens and did not realize was trying to decode from there specifically. I assumed it'd be the entire payload. 

Once again, thanks for putting this out there. I'm definitely open to help address these if you can point me in the right direction!

**Comment by jkarni** [comment] 2017-08-21 12:19
Sorry for the delay - just got back from a long period away from the internet.

There already is a note about `dat` here: 
https://github.com/plow-technologies/servant-auth/blob/ffa4c29c86f4deca8e183f2fb426e660e4551d9a/servant-auth-server/src/Servant/Auth/Server/Internal/JWT.hs#L36-40
- do you think there is a more appropriate place? Or is that sufficient? If it
is, can I change the title of the issue?

You're right that there should be more information about what failed in
`AuthResult`. I think changing the `Indefinite` constructor to `Indefinite
[T.Text]` (or something more structured, as long as it isn't JWT-specific)
would be the way to go. Then at the section you referenced we can give a more
specific description.

Would you still be willing to send a PR?

**Comment by jetaggart** [comment] 2017-08-22 16:19
Yeah, I will take a stab at it. We're in crunch time right now so it'll likely be a few weeks, but this is definitely important for us as we use a third party identity provider and the payload is subject to change.

**Comment by psylinse** [comment] 2018-07-04 19:01
Hey, I never got around to this and am no longer using `servant`. Want me to leave this open or go ahead and close this issue?

**Comment by domenkozar** [comment] 2018-07-04 22:11
It's a duplicate of #78 anyway - thanks!

**Closed by domenkozar** 2018-07-04 22:11 UTC
